name: Deploy MultiDocker
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t 0xcr/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true 0xcr/react-test npm test
 
      - run: docker build -t 0xcr/multi-client ./client
      - run: docker build -t 0xcr/multi-nginx ./nginx
      - run: docker build -t 0xcr/multi-server ./server
      - run: docker build -t 0xcr/multi-worker ./worker
 
      - run: docker push 0xcr/multi-client
      - run: docker push 0xcr/multi-nginx
      - run: docker push 0xcr/multi-server
      - run: docker push 0xcr/multi-worker
